# MySQL properties
db.driver=com.mysql.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/pwi
db.username=pwiusr
db.password=pwi123

# Hibernate properties
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update